export const INIT_HEATMAP = 'INIT_HEATMAP';
export const UPDATE_HEATMAP = 'UPDATE_HEATMAP';
export const UPDATE_DEVICES_HEATMAP = 'UPDATE_DEVICES_HEATMAP';
export const UPDATE_ACCESSPOINTS_HEATMAP = 'UPDATE_ACCESSPOINTS_HEATMAP';
export const LOADDATA_HEATMAP = "LOADDATA_HEATMAP";

export const UPDATE_MAP_POSITION = 'UPDATE_MAP_POSITION';
export const INIT_MAP = 'INIT_MAP';
export const INIT_HEATMAPLAYER = 'INIT_HEATMAPLAYER';
export const INIT_DRAWINGTOOLS = 'INIT_DRAWINGTOOLS';
export const UPDATE_MAP = 'UPDATE_MAP';
export const LOAD_MAP = 'LOAD_MAP';
export const LOAD_HEATMAPLAYER_DEVICE_DATA = 'LOAD_HEATMAPLAYER_DEVICE_DATA';
export const LOAD_HEATMAPLAYER_ACCESSPOINT_DATA = 'LOAD_HEATMAPLAYER_ACCESSPOINT_DATA';
