export const INIT_HEATMAP = 'INIT_HEATMAP';
export const UPDATE_HEATMAP = 'UPDATE_HEATMAP';
export const UPDATE_DEVICES_HEATMAP = 'UPDATE_DEVICES_HEATMAP';
export const UPDATE_ACCESSPOINTS_HEATMAP = 'UPDATE_ACCESSPOINTS_HEATMAP';
export const LOADDATA_HEATMAP = "LOADDATA_HEATMAP";
