// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9b5329839558a78550bf078c3e5f323c2f0f3b86/react-scrollbar/index.d.ts
declare module "react-scrollbar" {
  interface ScrollAreaProps extends React.Props<ScrollArea> {
      className?: string,
      style?: React.CSSProperties,
      speed?: number,
      contentClassName?: string,
      contentStyle?: React.CSSProperties,
      vertical?: boolean,
      verticalContainerStyle?: React.CSSProperties,
      verticalScrollbarStyle?: React.CSSProperties,
      horizontal?: boolean,
      horizontalContainerStyle?: React.CSSProperties,
      horizontalScrollbarStyle?: React.CSSProperties,
      onScroll?: (value: {leftPosition: number, topPosition: number, containerHeight: number, containerWidth: number, realHeight: number, realWidth: number}) => void,
      contentWindow?: any,
      ownerDocument?: any,
      smoothScrolling?: boolean
      minScrollSize?: number,
      swapWheelAxes?: boolean
  }

  class ScrollArea extends React.Component<ScrollAreaProps, {}> {}

  export = ScrollArea;
}
